import random

dist = [
[0,10,15,20,25,30,35,40],
[12,0,35,15,20,25,30,45],
[25,30,0,10,40,20,15,35],
[18,25,12,0,15,30,20,10],
[22,18,28,20,0,15,25,30],
[35,22,18,28,12,0,40,20],
[30,35,22,18,28,32,0,15],
[40,28,35,22,18,25,12,0]
]

cities = list(range(8))   # cities 0-7


def cost(path):

    total = 0

    for i in range(len(path)-1):
        total += dist[path[i]][path[i+1]]

    # return to start
    total += dist[path[-1]][path[0]]

    return total

#neighbours are generated by swapping 2 cities in the path
def neighbors(path):

    neigh = []

    for i in range(1,len(path)):
        for j in range(i+1,len(path)):

            new_path = path.copy()

            new_path[i], new_path[j] = new_path[j], new_path[i]

            neigh.append(new_path)

    return neigh


def beam_search(k):

    # create k random initial tours
    beams = []

    for _ in range(k):
        path = cities.copy()
        random.shuffle(path)
        beams.append(path)

    for step in range(0):

        all_neighbors = []

        for path in beams:
            all_neighbors.extend(neighbors(path))

        # sort by cost
        all_neighbors.sort(key=cost)

        # keep best k
        beams = all_neighbors[:k]

    best = min(beams, key=cost)

    return best, cost(best)


# Run for different beam widths

for k in [3,5,10]:

    path, c = beam_search(k)

    print("Beam width:",k)
    print("Best path:",path)
    print("Cost:",c)
    print()